import = ["/home/prajwal.adhikari@tekvortex.local/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "Firacode NerdFont"
style = "Bold"

[font.italic]
family = "Firacode NerdFont"
style = "Italic"

[font.normal]
family = "Firacode NerdFont"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
dynamic_title = false

[window.dimensions]
columns = 125
lines = 30

[window.padding]
x = 5
y = 0

